[theme]
base = "light"
primaryColor = "#558b2f"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#f0f0f0"
textColor = "#1a1a1a"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"
